#!/usr/bin/env python

Import("env")
Import("env_modules")

env_wasm = env_modules.Clone()

# Check for WAMR in thirdparty directory.
import os

wamr_include_path = os.path.join(Dir("#").abspath, "thirdparty", "wamr", "core", "iwasm", "include")
wamr_available = os.path.isdir(wamr_include_path)

if wamr_available:
    env_wasm.Append(CPPDEFINES=["WAMR_ENABLED"])
    env_wasm.Prepend(CPPPATH=[wamr_include_path])

env_wasm.add_source_files(env.modules_sources, "*.cpp")

if env["tools"]:
    env_wasm.add_source_files(env.modules_sources, "editor/*.cpp")
